## The makeCacheMatrix function creates a special "matrix" object that can cache its inverse
## The cacheSolve function computes the inverse of the special "matrix" returned by makeCacheMatrix above. If the inverse has already been calculated (and the matrix has not changed), then the cachesolve should retrieve the inverse from the cache.
## Example- calculate the inverse matrix of a simple matrix x
# x<- matrix(nrow=2, ncol =2, 1:4) 
# ma <- makeCacheMatrix(x)
##  cacheSolve(ma)

makeCacheMatrix <- function(x = matrix()) {
        cacheInverse <- NULL
        set <- function(y) {
                x <<- y
                cacheInverse <<- NULL
        }
        get <- function() x
        setInverse <- function(inverse) cachedInverse <<- inverse
        getInverse <- function() cacheInverse
        list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}


## The function is used for catching the inverse matrix generated by makecacheMatrix function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inversed <- x$getInverse()
        if(!is.null(inversed)) {
                message("getting cached data")
                return(inversed)
        }
        
        data <- x$get() # get the matrix from the object
        inversed <- solve(data) %*% data # calculate inverse 
        x$setInverse(inversed) # set the inverse to the object
        inversed 
}

